version: 2
updates:
  # Enable version updates for npm in the root directory
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"
    # Optional: Add labels to Dependabot PRs
    labels:
      - "dependencies"
      - "dependabot"
    # Ignore updates for tailwindcss >= v4 due to build issues
    ignore:
      - dependency-name: "tailwindcss"
        versions: [">= 4.0.0"]

  # Enable version updates for npm in the server directory
  - package-ecosystem: "npm"
    directory: "/server"
    schedule:
      interval: "daily"
    target-branch: "main"
    labels:
      - "dependencies"
      - "dependabot" 