name: Create Release

on:
  push:
    tags:
      - 'v*.*.*' # Trigger on version tags like v1.0.0, v1.2.3, etc.

permissions:
  contents: write # Needed to create releases

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x' # Match the CI workflow version
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test # Important: Ensure tests pass before releasing

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2 # Popular action for creating releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Provided by GitHub Actions
        with:
          draft: true # Create the release as a draft initially
          # Optionally, you can generate release notes automatically:
          # generate_release_notes: true
          # Assets can be uploaded later if needed, e.g.:
          # files: |
          #   ./release-*.zip 